### ISSUE TITLE
Might be useful to add JsonPointer equality

### ISSUE THREAD

**Issue by nullrocket** [f3ath/rfc-6901-dart#1]
It would be handy if we could do the following.
```dart
JsonPointer thisPointer("/some/path");
JsonPointer thatPointer("/some/path");

if(thisPointer == thatPointer) {
...

}
```
I've written a few extension methods to  add some utility functions like equals, but equality is probably better off overriding the == operator and hashcode in the library.

```dart
JsonPointer thisPointer("/some/path");
JsonPointer thatPointer("/some/path");

if(thisPointer.equals(thatPoiinter)) {
...

}
```

**Comment by f3ath** [comment]
Good point. Mind opening a PR?

**Comment by nullrocket** [comment]
Will do, might be a day or two.  Any interest in adding some of the extension methods?  There are a few that are generally useful.  If so I will open another issue to discuss.

```dart
JsonPointer thisPointer("/some/path");
JsonPointer thatPointer("/some/path/a");

thatPointer.isWithin( thisPointer ); // -> true
thisPointer.isWithin( thatPointer ); // ->  false
thisPointer.isWithin( thisPointer ); // -> false

```

**Comment by f3ath** [comment]
Sure. Do they have to be extensions though? Everything seems to be straightforward enough to add this as regular class methods.

**Comment by nullrocket** [comment]
Nope, they don't have to be extensions at all,  that's just how I implemented them to avoid forking since I wasn't sure which ones conceptually belonged at the pointer level yet.  After using it a bit I'm finding that a  number of path comparison / manipulation concepts probably do belong.

Pull request on this actual issue https://github.com/f3ath/rfc-6901-dart/pull/2

**Comment by f3ath** [comment]
Thank you! Released https://pub.dev/packages/rfc_6901/versions/0.1.1

**Comment by nullrocket** [comment]
Thanks!  I appreciate it.  This is a handy package.
